"""add company and refresh token

Revision ID: a0785de3133b
Revises: e8c4f0f6b2a1
Create Date: 2026-07-13 23:04:43.351806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0785de3133b'
down_revision: Union[str, Sequence[str], None] = 'e8c4f0f6b2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_index(op.f('ix_billing_events_id'), 'billing_events', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.drop_index(op.f('ix_BillingEvents_id'), table_name='BillingEvents')
    op.drop_table('BillingEvents')
    op.add_column('conversations', sa.Column('initiateur_id', sa.Integer(), nullable=False))
    op.add_column('conversations', sa.Column('destinataire_id', sa.Integer(), nullable=False))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('conversations_user2_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_user1_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['initiateur_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['destinataire_id'], ['id'])
    op.drop_column('conversations', 'user1_id')
    op.drop_column('conversations', 'user2_id')
    op.add_column('messages', sa.Column('expediteur_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('document_url', sa.String(length=500), nullable=True))
    op.alter_column('messages', 'contenu',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['expediteur_id'], ['id'])
    op.drop_column('messages', 'sender_id')
    op.create_unique_constraint(None, 'user_quotas', ['user_id'])
    op.drop_column('user_quotas', 'chats_limit')
    op.drop_column('user_quotas', 'chats_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_quotas', sa.Column('chats_used', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_quotas', sa.Column('chats_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_quotas', type_='unique')
    op.add_column('messages', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.alter_column('messages', 'contenu',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'document_url')
    op.drop_column('messages', 'expediteur_id')
    op.add_column('conversations', sa.Column('user2_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('user1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user1_id_fkey'), 'conversations', 'users', ['user1_id'], ['id'])
    op.create_foreign_key(op.f('conversations_user2_id_fkey'), 'conversations', 'users', ['user2_id'], ['id'])
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'destinataire_id')
    op.drop_column('conversations', 'initiateur_id')
    op.create_table('BillingEvents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('stripe_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_debut', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('BillingEvents_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('BillingEvents_pkey'))
    )
    op.create_index(op.f('ix_BillingEvents_id'), 'BillingEvents', ['id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_billing_events_id'), table_name='billing_events')
    op.drop_table('billing_events')
    # ### end Alembic commands ###
